[tasks.fmt]
run = """
for file in */**/*.cue; do
  cue fmt "$file"
done
"""

[tasks.build]
run = """
docker build -t argocd-cmp-timoni:latest ./argocd-cmp-timoni
"""

[tasks.redeploy]
run = """
set -eo pipefail
docker build -t argocd-cmp-timoni:latest ./argocd-cmp-timoni
kind load docker-image argocd-cmp-timoni:latest
kubectl apply -k ./argocd
kubectl rollout restart deployment argocd-repo-server -n argocd
"""

[tasks.lint]
run = """
APP_NAMESPACE=test timoni bundle vet -f workloads/timoni-bundle/bundle.cue --runtime-from-env
"""
