---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "common.names.fullname" .) .Values.serviceAccount.name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
automountServiceAccountToken: false
