---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - resources/namespace.yaml
  - resources/cmp-plugin.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.9/manifests/install.yaml
patches:
  - path: patches/repo-server.yaml
